### ISSUE TITLE
vaga de backend-fullstack

### ISSUE THREAD

**Issue by mcoimbrac** [HotelUrbano/vagas#7]
# Marcelo Coimbra Coelho

|   |   |   |
|---|---|--:|
| Rua Viscondessa de Pirassununga |   | mcoimbrac@yahoo.com |
| Rio de Janeiro - 20211-100 |    | @mcoimbrac |
| Brazil |    |  |

## Educação

- **Ciencia da computação**
 ```
  2007-2013 - Unicarioca
  Título do trabalho final: Geolocalização para logística
 ```

## Experiência

**Denke**
```
  Atuei no desenvolvimento de projetos internos/externos, na pesquisa de novas ferramentas e tecnologias e na implantação das tecnologias que julgavamos ser boas para o nosso stack (ex: vpn, docker, kubernetes).

  * Desenvolvimento de projetos utilizando NodeJS, php, python, .Net, mono, C#, javascript, shellscript, html, css.
  * Bancos de dados sql/nosql: mysql, postgresql, sql server, influxdb, redis, mongo, couchdb, pouchdb, memcache, etc.
  * Execução de testes de performance, funcional, integração, unitários: apache ab, jmeter, siege, scripts, mocha, chai
  * Pesquisa e avaliação de ferramentas e ambientes (Paas, Iaas), continuous deploy/integration (jenkins, git hooks), git servers (gitlab, gogs, gitbucket, bonobo), monitoração (fluentd, kibana, grafana).
  * Implantação do ambiente de desenvolvimento atual utilizando docker, openshift v3 (kubernetes), aws, openvpn, git credentials, repositorios privados (npm, bower, nuget).
  * Administração de repositórios de projetos internos e externos.
  * Administração de infra em cloud (azure, aws, openshift).
  * Administração e configuração de servidores (ubuntu, centos).
  * Pesquisa, avaliação e implantação de novas soluções, frameworks, ferramentas.
  * Execução de projetos para clientes externos.
    * [https://ondeinvestir.lopesfilho.com.br](https://ondeinvestir.lopesfilho.com.br)
  * Elaboração de documentações.
```

**MSA Consultoria em RH**
```
  Atuei no desenvolvimento de sistemas voltados pra cliente externo (Vale), e na administração dos ativos da MSA. Era o responsável técnico pelos sistemas, infra e equipe de TI

  * Desenvolvimento com PHP5, PostgreSQL, HTML/CSS, Javascript, ShellScripting e Java.
  * Administração dos repositórios Git.
  * Administração, manutenção, tunning e hardening dos bancos de dados PostgreSQL.
  * Líder de desenvolvimento de projetos:
      * https://www.programatransformar.com.br
      * http://www.qualificacaotecnica.com.br
  * Pesquisa e implantação de novas soluções/frameworks.
  * Administração dos ativos da rede, e dos servidores em cloud.
  * Planejamento, execução e coordenação de projetos de TI.
  * Coordenação de equipe de suporte e desenvolvimento.
  * Treinamento e supervisão de estagiários e juniores.
  * Elaboração de documentações e políticas. Apoio gerencial.
  * Viagens/visitas a filiais para solução de problemas de infra.
```

**Cipher - Segurança da Informação**
```
  Atividades de consultoria em infraestrutura e segurança da informação

  * Consultoria de Segurança / Administração de Redes / Analista de Suporte.
  * Administração, instalação e manutenção de servidores (Linux, Windows / Active Directory, DFS, DNS, DHCP).
  * Atividades remotas (Terminal Server, VPN, SSH) e presenciais.
  * Instalação e configuração de Bancos de dados (PostGreSQL, MySQL, SQL Server, MSDE);
  * Hardening, análise de logs, análise de perímetro.
  * Instalação, configuração e gerenciamento de ferramentas de segurança (Firewall, Proxy, IDS/IPS, Anti Virus corporativo, Filtro web, Mail Gateway, ferramentas de autenticação forte, Patch Management, Single SignOn);
  * Utilização de VMWare para ambientes de laboratório. Soluções de rede, infra e de segurança.
  * Elaboração de políticas.
  * Pesquisas. Documentações.
  * Elaboração de propostas técnicas.

```

**MSA Consultoria em RH**
```
  * Análise e desenvolvimento de sistemas web utilizando PHP4 e MySQL, sistemas em Access, e desenvolvimento do site www.msarh.com.br.
  * Interface na customização das ferramentas operacionais
  * Automação de tarefas operacionais com Java
  * Operação de central telefônica modelo Siemens HiPath 3550 para gerenciamento da telefonia.
  * Treinamentos de usuários
  * Elaboração de relatórios gerenciais.
  * Suporte e Manutenção de estações Windows e servidor de arquivos Debian;
  * Coordenação da equipe de suporte.
```

**GWM - Auditores e Consultores**
```
  * Desenvolvimento e manutenção de sistemas de gestão fiscal, de contabilidade e de Recursos Humanos em ASP, JavaScript, SQL Server e CSS.
```

**Sociedade Brasileira de Cardiologia (www.cardiol.br)**
```
  * Administração de rede e suporte.
  * Administração/manutenção de servidores (Windows NT/2000, Netware, IIS, Apache, DNS)
  * Instalação e configuração de servidores (DNS, IIS, SQL Server, Antivírus para e-mail), e estações (Windows 9x/2000);
  * Banco de dados (Access, SQL Server);
  * Redes:
     * Segurança: Firewall, IDS, Políticas;
     * Instalação e Manutenção - Configuração, cabeamento, diagramação, documentação
  * Políticas / rotinas de backup / disaster-recovery usando ArcServeIT e de segurança (Vírus - detecção, prevenção e remoção; falhas de segurança e de softwares - Service Packs, atualizações críticas, políticas de Firewall e IDS).
  * Operação da central telefônica Alcatel
  * Instalação da rede dos estandes do 57º Congresso Nacional de Cardiologia, em setembro de 2002 em São Paulo, com a implementação de novos serviços que visavam comunicar os dispositivos dos congressistas (Palms); coleta de dados através de máquinas coletoras dispostas pelo galpão para armazenamento em uma base de dados centralizada.
```

#### Meus projetos paralelos

 - Projetos pessoais no bitbucket

#### Open Source

 - [Azure/autorest](https://github.com/Azure/autorest)
   - report de um bug que causava um estouro de pilha, e como reproduzi-lo:
     - https://github.com/mcoimbrac/autorest-sample
     - https://github.com/Azure/autorest/issues/919
 - [mcoimbrac/wallet-reporter](https://github.com/mcoimbrac)
   - ferramenta (em dev) pra auxiliar a gerenciar as cryptomoedas existentes nas wallets das exchanges

#### Linguagens de programação e ferramentas
 -  **NodeJS:** Desde 2013, versão 0.8.x. Conheço bem, e gosto muito do gerenciamento de pacotes do NPM

 -  **PHP:** Trabalho com PHP desde a versão 4, ainda em 2004. Na época era ela ou ASP, e isso me rendeu um bom conhecimento nela. Apesar de não gostar muito dela após ter contato com outras como python, ruby e nodejs.

 -  **Java** Conheço Java desde a versão 1.2, quando começou a se chamar J2SE/J2EE. Na época não tirei a certificação por falta de dinheiro. Me rendeu uma boa base nela que me ajuda até hoje.
 -  **Python** Comecei a ter contato com Python em 2012, e desde então sempre que posso o utilizo para me auxiliar a automatizar tarefas
 -  **Shellscript** Trabalho com shell/bash script desde que comecei a ter contato com linux. Uso para auxiliar/automatizar tarefas, reduzir comandos, etc
 -  **Ruby** Comecei a ter mais contato com Ruby em 2013, quando passei a utilizar o Gitlab como servidor de git onde trabalhava. Precisava customizar algumas coisas e o gitlab era todo feito em ruby.

 -  **MySQL** Comecei a ter contato com o MySQL ainda em 2003, e posteriormente em 2004 já em no desenvolvimento de um sistema de banco de curriculos com PHP4
 -  **Postgres** A minha experiência com Postgres se iniciou em 2006, quando comecei a trabalhar como freelancer em um projeto de aluguel de imóveis, e posteriormente, meu contato passou a ser mais intenso em 2008, no desenvolvimento de sistemas com um banco relacional grande, que ainda são usados pela Vale
 -  **SQL Server** Conheci o SQL Server ainda no começo de 2002, no meu primeiro trabalho em contato com tecnologia. Era o banco utilizado no portal onde trabalhava e posteriormente quando fui trabalhar com ASP. Ainda em 2012, era o banco utilizado por um dos clientes da Denke, e apesar de não ter participado da elaboração dele, ainda cuidava da administração ocasional e da extração de dados dele
 -  **Redis** A partir de 2012, em vários projetos. O gitlab por exemplo precisa de uma instancia do Redis para melhor performance. A idéia do Redis é genial, mas acredito que o consumo de memória que ele exige é o maior ponto negativo dele
 -  **CouchDB** Em 2012, quando passei a pesquisar alternativas para implementar um repositório NPM privado, acabei tendo bastante contato com o CouchDB
 -  **PouchDB** Uma das interfaces da plataforma que a Denke estava criando era mobile, utilizando Ionic com PouchDB. Trabalhei bastante em uma solução que buscava fazer uma sincronização/replicação entre dados do PouchDB para um banco interno
 -  **MongoDB** A partir de 2012, quando precisava de um banco que armazenasse dados em JSON

 -  Conhecimentos básicos: **GoLang**, **C#/Mono**, **C**

## Idiomas
  * Português (nativo).
  * Inglês (fluente)

## Seção Extra, diga o que você quiser

- Adoro aprender coisas novas e gosto de ajudar

- Gosto de cryptocurrencies. Isso quando não as odeio :)

- E achei genial o .bf no repositório (`\o/ hotelurbano.com - Tirou onda!`).

**Comment by zanaca** [comment]
CV recebido!
