### ISSUE TITLE
backend-fullstack

### ISSUE THREAD

**Issue by luizfelipebrito** [HotelUrbano/vagas#8]
```javascript
/***
* - Escreva seu currículo, conte sua história, logo abaixo. Não use apenas links para sites externos,
*   a maneira como você o fizer vai ajudar!
* - Use a formatação de markdown, beleza não é tudo, mas ajuda ;)
*   https://guides.github.com/features/mastering-markdown/
* - Retire os comentários
*/
```
# Luiz Felipe de Almeida Brito

|   |   |   |
|---|---|--:|
| 47, Horácio Alves Barbosa Street |   | luiz.brito.rj@hotmail.com |
| Campo Grande - Rio de Janeiro – RJ – 23071-100 |    | https://github.com/luizfelipebrito |
| Brazil |    | 1800 21 989390480 |

## Educação

- **Master of Project Management**
 ```
  2011-2012 - FGV-RJ – Rio de Janeiro – Brazil
  Título do trabalho final: Negociação e Comunicação no Gerenciamento de Projetos
 ```

- **Bachelor Degree in Information Technology**
 ```
  1996-2000 -  PUC-RJ – Rio de Janeiro – Brazil
  Título do trabalho final: Automatização de uma fazenda de Cacau
 ```

## Experiência

**BTG Pactual - (July/2003 to July 2012) - Investment bank with a dominant franchise in Latin America.**

Position: Project Manager
Responsible for organising and managing resources such that all IT projects are delivered within the defined scope, time and quality. As project manager, established and maintained all project plans, served as primary contact with outside vendors/consulting firms; and led team of analysts/consultants.

* Primeiro item
Below I stand out four projects in which I acted during my time at BTG Pactual.
1. Integration with the Central Bank of Brazil’ new system information: I led the team responsible for adapting its communication system with the new technology platform of Central Bank of Brazil. This project was a legal demand set by Central Bank of Brazil, which required that all Brazilian financial institutions must adopt. The PMO and a committee were the main project sponsors to which I reported weekly through status reports and conference calls. The highest risk of this project was to manage conflicts for resource allocations. This project lasted one year and it was necessary to allocate around 20 people (all intern resource).
2. Exchange System: My role in this project was to manage the replacement of a legacy system that was developed and supported in-house for 20 years by a new system supplied by a third party. The project was an internal demand, lasted seven months and its keys stakeholders were the following departments: Finance, Treasury, Fixed Income, Assets Management and Equity. The big challenge for this project was the communication management that involved stakeholders internal and external. The communication management was conducted through meeting with stakeholders, service request control, and status report weekly. The win-win negation approach was one of the ways that I found to obtain internal resources and set internal deadlines. 
3. Merging with UBS Bank: I was responsible for the project of the integration of Wealth Management’s system. This project had a high operational risk because as the Wealth Management’s system sends information to customers, I had to ensure that all changes we had made in order to integrate the systems would not have caused any incorrect information. To minimize this risk we formed a rigorous testing plan. This project took approximately ten months and had as the main sponsor the Director of Wealth Manager to whom I reported the project’s progress through regular fortnightly meetings.
4. Custom Report System: I had been part of the team that developed the system responsible for generating the monthly bank statements. The bank statement consolidates information from various markets as investment funds, fixed income, equity and current account in a single document. Due to the fact that this information came from different systems, there was a high risk of incorrect information being sent out to customers. The project involved around fifty people directly and indirectly and took approximately eight months.

#### Open Source
:   https://github.com/luizfelipebrito/datasciencecoursera

#### Linguagens de programação e ferramentas
 -  **Strong SQL skills for data validation, analysis, and DDL script generation for DBA teams.,

 -  **UML, Oracle (PL/SQL), Microsoft WCF, Microsoft Visual Studio, Microsoft TFS, Microsoft VB, Microsoft Office(VBA), Microsoft SQL Server, Microsoft .NET, Microsoft Project and Microsoft Test Manager.

## Idiomas
  * Português (nativo).
  * Inglês (fluente);

## Seção Extra, diga o que você quiser

Referees
Clinton Woodhouse – Mobile: +61 07 0430 860 246  (Australia)  woodhouseclinton@gmail.com
Alana Jessop           – Phone: +61 07 3254 9501  (Australia)  alana.jessop@artslinkqld.com.au
Alfredo Silva            – Phone: +55 21 981315173 (Brazil)   alfredo.silva@btgpactual.com
Mario Soares           – Phone: +55 21 981315820 (Brazil)   mario_soares@globo.com

**Comment by zanaca** [comment]
CV recebido!
